Fix formatting

diff --git a/bin/.local/bin/countdown b/bin/.local/bin/countdown
--- a/bin/.local/bin/countdown
+++ b/bin/.local/bin/countdown
@@ -7,13 +7,12 @@ if [ -z "$1" ]; then
 fi
 
 if ! [[ "$count" =~ ^[0-9]+$ ]]; then
-  echo "Error: Starting number must be a positive integer."
-  exit 1
+    echo "Error: Starting number must be a positive integer."
+    exit 1
 fi
 
-while [ $count -gt 0 ]
-do
-    echo $count
+while [ "$count" -gt 0 ]; do
+    echo "$count"
     count=$((count - 1))
     sleep 1
 done
